#!/bin/bash

# build variables
htop_master_branch="main"
htop_binaries="htop"
htop_configure_options="--enable-static \
  --disable-unicode \
  --disable-hwloc \
  --disable-sensors \
  --disable-capabilities \
  --disable-openvz \
  --disable-vserver \
  --disable-ancient-vserver \
  --disable-delayacct"
htop_make_options=""
htop_aarch64="$(uname -m | grep -q 'aarch64' && echo gcc)"
htop_arm="no"

# package variables
htop_Depends="libncurses"
htop_License="GPL-2.0-or-later"
htop_Section="admin"
htop_Description="  Htop is an ncursed-based process viewer similar to top, but
 it allows to scroll the list vertically and horizontally to
 see all processes and their full command lines."

htop_popd() {
  popd
}

htop_pushd() {
  if [ ! -d htop ]; then
    git clone --depth 1 https://github.com/htop-dev/htop.git
  fi
  pushd htop
}

htop_version() {
  git describe --tags $(git rev-list --tags --max-count=1)
}
