#!/bin/bash

# build variables
htop_binaries="htop"
htop_configure_options="--enable-static --disable-unicode --disable-hwloc --disable-setuid --disable-sensors --disable-capabilities --disable-openvz --disable-vserver --disable-ancient-vserver --disable-delayacct --disable-linux-affinity"
htop_make_options=""

# package variables
htop_Depends="libncurses"
htop_License="GPL-2.0-or-later"
htop_Section="admin"
htop_Maintainer="Etienne CHAMPETIER <champetier.etienne@gmail.com>"
htop_Description="  Htop is an ncursed-based process viewer similar to top, but
 it allows to scroll the list vertically and horizontally to
 see all processes and their full command lines."

htop_dependencies() {
  # Either:
  # - call the check_package function with the name of an executable and the required package; OR
  # - APPEND to the __PACKAGES global variable
  check_package ncurses5-config libncurses5-dev
}

htop_pushd() {
  # Clone the repository if the directory does not exist
  if [ ! -d htop ]; then
    git clone --depth 1 https://github.com/htop-dev/htop.git
  fi
  # ALL {scriptname}_pushd functions MUST end with the pushd command!
  pushd htop
}
