#!/bin/bash

# build variables
iperf3_binaries="src/iperf3"
iperf3_configure_options="--disable-shared --enable-static --enable-static-bin"
iperf3_make_options=""
iperf3_aarch64="$(uname -m | grep -q 'aarch64' || echo no)"
iperf3_arm="$(uname -m | grep -q 'armv[567]' || echo no)"

# package variables
iperf3_Depends=""
iperf3_License="BSD-3-Clause"
iperf3_Section="net"
iperf3_Description="  Iperf is a modern alternative for measuring TCP and UDP bandwidth
 performance, allowing the tuning of various parameters and
 characteristics."

iperf3_add_files() {
  mkdir -p etc/config
  cat <<-"CONF" > etc/config/iperf
config iperf 'iperf'
        option proto 'TCP'
        option dest_port '5001'
        option enabled '0'
CONF

  mkdir -p etc/init.d
  cat <<-"INIT" > etc/init.d/iperf
#!/bin/sh /etc/rc.common

START=70
STOP=10
USE_PROCD=1

. $IPKG_INSTROOT/lib/functions.sh

start_service() {
    local enabled=$(uci_get iperf iperf enabled 0)
    local protocol=$(uci_get iperf iperf proto TCP)
    local port=$(uci_get iperf iperf dest_port 5001)

    if [ "$protocol" = "UDP" ]; then
        proto="-u"
    else
        proto=""
    fi

    if [ "$enabled" = "1" ]; then
        uci_toggle_state "iperf" "iperf" "status" "Enabled"
        procd_open_instance
        procd_set_param command /usr/bin/iperf3 -s $proto -p $port
        procd_set_param respawn 60, 60, 0
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
    else
        uci_toggle_state "iperf" "iperf" "status" "Disabled"
    fi
}

stop_service() {
    local enabled=$(uci_get iperf iperf enabled 0)

    if [ "$enabled" == "1" ]; then
        kill -9 `ps | grep '[i]perf3 -s' | awk '{print $1}'`
    fi
}
INIT
  chmod +x etc/init.d/iperf
}

iperf3_conffiles() {
  echo "/etc/config/iperf"
}

iperf3_popd() {
  popd
}

iperf3_pushd() {
  if [ ! -d iperf ]; then
    git clone --depth 1 https://github.com/esnet/iperf.git
  fi
  pushd iperf
}

iperf3_version() {
  sed -rn 's|(.*)\[(.*)],\[https://github.com/esnet/iperf],(.*)|\2|p' configure.ac
}
