#!/bin/bash

# build variables
rsync_binaries="rsync"
rsync_configure_options="--without-included-popt \
  --without-included-zlib \
  --disable-debug \
  --disable-asm \
  --disable-lz4 \
  --disable-locale \
  --disable-md2man \
  --disable-openssl \
  --disable-simd \
  --disable-roll-simd \
  --disable-xxhash \
  --disable-iconv \
  --disable-iconv-open \
  --disable-zstd \
  --disable-xattr-support \
  --disable-acl-support"

# package variables
rsync_Depends="zlib"
rsync_License="GPL-3.0-or-later"
rsync_Section="net"
rsync_Description="  rsync is a program that allows files to be copied to and from remote machines
 in much the same way as rcp. It has many more options than rcp, and uses the
 rsync remote-update protocol to greatly speed up file transfers when the
 destination file already exists.

 The rsync remote-update protocol allows rsync to transfer just the differences
 between two sets of files across the network link."

rsync_popd() {
  popd
}

rsync_pushd() {
  if [ ! -d rsync ]; then
    git clone --depth 1 https://github.com/WayneD/rsync.git
  fi
  pushd rsync
}

rsync_version() {
  git tag -l | grep -v pre | tail -n 1
}
